import './assets/vendors/bootstrap/css/bootstrap.min.css'
import './assets/vendors/bootstrap-select/bootstrap-select.min.css'
import './assets/vendors/animate/animate.min.css'
import './assets/vendors/fontawesome/css/all.min.css'
import './assets/vendors/jquery-ui/jquery-ui.css'
import './assets/vendors/jarallax/jarallax.css'
import './assets/vendors/jquery-magnific-popup/jquery.magnific-popup.css'
import './assets/vendors/nouislider/nouislider.min.css'
import './assets/vendors/nouislider/nouislider.pips.css'
import './assets/vendors/tiny-slider/tiny-slider.css'
import './assets/vendors/floens-icons/style.css'
import './assets/vendors/swiper/css/swiper-bundle.min.css'
import './assets/vendors/owl-carousel/css/owl.carousel.min.css'
import './assets/vendors/owl-carousel/css/owl.theme.default.min.css'
import './assets/vendors/slick/slick.css'
import './assets/css/floens.css'
import './assets/css/floens-dark.css'

import { createApp } from 'vue'
import App from './App.vue'
import router from './router'

createApp(App).use(router).mount('#app')
